### ISSUE TITLE
change readd 1.16 when and change it to 1.17 when

### ISSUE THREAD

**Issue by bigratenthusiast** [bigratmonster/bigrat.monster#33]
title

**Comment by SoNothingMC** [comment]
we can do that, but we can't keep the video since Cloudflare pages doesn't allow files >30MB
(the video also has `1.16` inside, and we can't change it since we don't have the original file :trollface:)

**Comment by ZimnyCat** [comment]
Cloudflare is user error

**Comment by humboldt123** [comment]
Closed due to inactivity.

**Comment by smokeytube** [comment]
![image](https://user-images.githubusercontent.com/67290867/128640273-32053327-7a0f-4f22-93f6-60db1ca8019f.png)
