### ISSUE TITLE
API

### ISSUE THREAD

**Issue by sourTaste000** [bigratmonster/bigrat.monster#4]
ex. choose a random image from the monkeys/ directory
or something lol

**Comment by sourTaste000** [comment]
oh this is the first issue? nice

**Comment by humboldt123** [comment]
That sounds great, why don't you make a pr :sunglasses:

**Comment by ricoip** [comment]
There's a reason why this repo has no "feature request" issue templates.

Because I do not have enough programming knowledge to implement stuffs like this 😥

**Comment by humboldt123** [comment]
Ill do it

**Comment by ricoip** [comment]
pogchamp

**Comment by humboldt123** [comment]
how 2 build A P I?????

**Comment by smokeytube** [comment]
is this a thing yet

**Comment by d1snin** [comment]
> Ill do it

use ktor

**Comment by d1snin** [comment]
https://github.com/ktorio/ktor

**Comment by smokeytube** [comment]
my tiny brain cant handle non-scripting languages

**Comment by Lolicon2110** [comment]
i might try something like that if skrub doesn't and i can figure it out :eyes:

**Comment by sourTaste000** [comment]
Nep nep why did u change name

**Comment by d1snin** [comment]
> Nep nep why did u change name

:trollface:

**Comment by NepNep21** [comment]
(big rat discord server) https://discord.com/channels/741333913183715528/741333913686769807/857992046992031764 :woeis:

**Comment by smokeytube** [comment]
so api when

**Comment by EmeraldSnorlax** [comment]
why is this even needed for static images
what would an api for this even do
and if there is an api, id assume it'd be serverless
