### ISSUE TITLE
Clear up meta tags

### ISSUE THREAD

**Issue by SoNothingMC** [bigratmonster/bigrat.monster#46]
Since our meta tags are generated, there are some redundant tags which can be removed.

I mean, who's gonna share bigrat on Facebook anyways?

**Comment by smokeytube** [comment]
what is the point of removing 2 lines from every file its not gonna make load times faster

**Comment by SoNothingMC** [comment]
> what is the point of removing 2 lines from every file its not gonna make load times faster

🤷‍♂️

**Comment by SoNothingMC** [comment]
okay lol idc anymore

**Comment by smokeytube** [comment]
Were you going to make the metatags more concise or were you going to remove the meta tags entirely?
