### ISSUE TITLE
[Feature Req] bigrat.monster official minecraft server

### ISSUE THREAD

**Issue by ayunami2000** [bigratmonster/bigrat.monster#50]
ill self host it

**Comment by smokeytube** [comment]
I thinm it is a good idema

**Comment by Cosmelon** [comment]
i agree

**Comment by ayunami2000** [comment]
whenever i make the server can u make a srv record to the main domain as well as to play.bigrat.monster (i dont have any ip at the moment for it but i can use *free hosting* for it!!)

**Comment by TudbuT** [comment]
poggers

**Comment by smokeytube** [comment]
> poggers

What are you doing here

**Comment by SupaGamer2017** [comment]
> poggers

@TudbuT, what the hell are you doing here?

**Comment by SoNothingMC** [comment]
Okay so there are actually 3 minecraft servers under the bigrat.monster domain, and all of them are currently private.

So I'm putting this on hold until all of them dies out (lol), then maybe we could just do one server for everything.

**Comment by SoNothingMC** [comment]
Hi - a status update:

**It looks like hosting a Minecraft server under bigrat.monster is no longer possible.**

Looking at the statistics, bigrat.monster gets DDOSed (currently once) every month with ~13 million requests in a day.

![A chart of bigrat.monster's overall traffic for July 2022 to August 2022, showing a 12.9 million request peak on 31st June 2022.](https://user-images.githubusercontent.com/32032824/185841481-3ea411cb-e403-4a40-b6c1-3eb1f4ef9de7.png)

If we host a server, the chance of a DDOS attack against the server would be very high, and may cause thousands of dollars in server ingress fees.  
The cons heavily outweigh the pros.

I don't want to bankrupt anyone, so although I like the idea very much, it unfortunately cannot be executed.

**Comment by literally1984** [comment]
@ayunami2000 who would have known that this man would go on to NOTT create piss shid mod for browser minecraft
