### ISSUE TITLE
Revise facts

### ISSUE THREAD

**Issue by HausemasterIssue** [bigratmonster/bigrat.monster#55]
Those aren't facts, those are studies or just slamming haters in a way. Not to mention the facts are mostly just bloat and really unnecessary. Something like Snapple facts may be more straightforward and nice.

**Comment by smokeytube** [comment]
1) bigratmonster doesn't own that document, someone else does.
2) they are facts, and the people who created the document put a lot of effort into putting together that document.

**Comment by smokeytube** [comment]
How's anything there edgy?
