### ISSUE TITLE
I am muted in the bigrat discord server

### ISSUE THREAD

**Issue by smokeytube** [bigratmonster/bigrat.monster#60]
**Describe the bug**
I am muted in the bigrat discord server

**To Reproduce**

1. Type in discord "Sonothint why keep only one channel open"
2. "Just open them all up"
3. "At this point"
4. Wait 1-2 days

**Expected behavior**
A clear and concise response, instead of being muted.

**Screenshots**
![image](https://user-images.githubusercontent.com/67290867/170104692-63f30024-5cff-40b0-b3c9-1bd210a684fa.png)

**Comment by SoNothingMC** [comment]
Sonothint why keep only one channel open

**Comment by SoNothingMC** [comment]
Just open them all up

**Comment by SoNothingMC** [comment]
At this point

**Comment by smokeytube** [comment]
It only works on discord!

**Comment by SoNothingMC** [comment]
> It only works on discord!

Hmm. That’s weird. Unfortunately, I can’t reproduce this issue anymore. I can see a few others doing it without any problems at all. I think it has been fixed on our side.

Thank you for reporting this bug!
