### ISSUE TITLE
Cannot buy merch

### ISSUE THREAD

**Issue by Joshua-Ashton** [bigratmonster/bigrat.monster#7]
**Describe the bug**
Clicking `Add to Cart` does nothing. Specifically I wanted to buy the Monster Rat Hoodie

**To Reproduce**
1. Go to https://merch.bigrat.monster
2. Click on any button to add to cart
3. Nothing happens

**Expected behavior**
The item is added to my cart and I am able to purchase the item(s) I selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/21316711/93849151-4e322780-fca3-11ea-9827-07e2f4724f71.png)

**Additional context**
I am using Firefox Nightly 81.0a1 on Windows 10 2004.

**Comment by ricoip** [comment]
LMFAO

**Comment by ricoip** [comment]
@humboldt123 Fix your joke button lmao

**Comment by ricoip** [comment]
But right now you can access the site with [this link](https://teespring.com/stores/bigrat), which is also on the bottom of the page
