### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by Scriptifer** [bigratmonster/bigrat.monster#76]
![bigrat](https://github.com/bigratmonster/bigrat.monster/assets/77464488/d3075704-ab14-4b9c-977e-26281a9b3916)
convert it to ico, the attachment is png

**Comment by SoNothingMC** [comment]
If I remember correctly, not having a favicon is originally a stylistic choice and is done on purpose.

However, I'll think about it again. Thanks for your recommendation.
