### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by rafal06** [bigratmonster/bigrat.monster#77]
**Describe the bug**
When accessing https://bigrat.monster, the server returns a 301 redirect response to the same address, resulting in a redirect loop

**To Reproduce**

1. Go to https://bigrat.monster
2. See error

**Expected behavior**
Picture of a big rat

**Screenshots**
![image](https://github.com/bigratmonster/bigrat.monster/assets/70489677/75e5aba5-0d1d-4fbf-9729-c0cf0195957d)
![image](https://github.com/bigratmonster/bigrat.monster/assets/70489677/e071ee32-9720-4b47-95b7-78758142ae31)

**Additional context**
I've tried doing a hard reload, but it didn't fix the problem

**Comment by SoNothingMC** [comment]
Hi! Thanks for bringing this to my attention. 

I have now verified a fix on my end (it seemed to be caused by [0-RTT Connection Resumption](https://developers.cloudflare.com/speed/optimization/protocol/0-rtt-connection-resumption/))

Can you verify if bigrat.monster is working on your machine?

**Comment by rafal06** [comment]
> Can you verify if bigrat.monster is working on your machine?
Yes, it works now, thanks!
